name:                aoc2021 
version:             0.1.0.0
github:              "ridgetinez/aoc2021"
license:             BSD3
author:              "Adrian Martinez"
maintainer:          "ridgetinez@gmail.com"
copyright:           "2021 Adrian Martinez"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ridgetinez/cryptopals#readme>

dependencies:
- base >= 4.7 && < 5
- text
- QuickCheck
- random
- transformers
- parsec

library:
  source-dirs: src
